---
takel_nodejs_deb_preinstall_packages:
  - ca-certificates
  - gnupg

takel_nodejs_deb_install_packages:
  - nodejs
  - npm

takel_nodejs_repository_key: >-
  https://deb.nodesource.com/gpgkey/nodesource.gpg.key
takel_nodejs_repository_filename: nodejs
takel_nodejs_repository_version: 17
takel_nodejs_repository_codename: bullseye
takel_nodejs_repository_url: >-
  https://deb.nodesource.com/node_{{ takel_nodejs_repository_version }}.x
takel_nodejs_repository: >-
  deb {{ takel_nodejs_repository_url }} {{
  takel_nodejs_repository_codename }} main

takel_nodejs_completion_dir: /etc/bash_completion.d
takel_nodejs_bash_completion: >-
  {{ takel_nodejs_completion_dir }}/nodejs
