---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint molecule/*/*.yml
  flake8
platforms:
  - name: molecule-takel-etherpad
    image: takelage/takelbase
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        takel_mysql_host: 127.0.0.1
        takel_mysql_port: 3306
        takel_mysql_etherpad_user: etherpad
        takel_mysql_etherpad_database: etherpad
        takel_mysql_etherpad_password: etherpad
        takel_mysql_user_my_cnf:
          - sys_home: /root
            sys_user: root
            sys_group: root
            mysql_host: localhost
            mysql_user: root
            mysql_password: root
          - sys_home: /var/opt/etherpad
            sys_user: etherpad
            sys_group: etherpad
            sys_shell: /bin/bash
            mysql_host: localhost
            mysql_user: etherpad
            mysql_password: etherpad
        takel_mysql_mysql_databases:
          - name: etherpad
        takel_mysql_mysql_users:
          - name: etherpad
            password: etherpad
            priv: etherpad.*:ALL
        takel_mysql_root_password: root
        takel_etherpad_mysql_host: 127.0.0.1
        takel_etherpad_mysql_user: etherpad
        takel_etherpad_mysql_password: etherpad
        takel_etherpad_mysql_database: etherpad
        takel_etherpad_admin_password: admin
        takel_etherpad_version: 0.0.1
  options:
    tags: takel_etherpad_bin
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../system/test_*.py
  options:
    # p: cacheprovider
    s: true
scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
