---
takel_base_deb_install_packages:
  - apt-transport-https
  - aptitude
  - ca-certificates
  - curl
  - gnupg
  - git
  - iproute2
  - iputils-ping
  - jq
  - locales
  - molly-guard
  - procps
  - rsync
  - rsyslog
  - tmux
  - tree
  - vim

takel_base_locales:
  - en_US.UTF-8
